<?php
/**
 * This file is automatic generated by build_docs.php file
 * and is used only for autocomplete in multiple IDE
 * don't modify manually.
 */

namespace danog\MadelineProto\Namespace;

interface Bots
{
    /**
     * Sends a custom request; for bots only
     *
     * @param string $custom_method The method name
     * @param array $params JSON-serialized method parameters @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * 
     *
     * @return array
     */
    public function sendCustomRequest(string $custom_method, array $params);

    /**
     * Answers a custom query; for bots only
     *
     * @param int $query_id Identifier of a custom query
     * @param array $data JSON-serialized answer to the query @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * 
     *
     * @return array
     */
    public function answerWebhookJSONQuery(int $query_id, array $data);

    /**
     * Set bot command list
     *
     * @param array $scope Command scope @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * @param string $lang_code Language code
     * @param array $commands Bot commands @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * 
     *
     * @return array
     */
    public function setBotCommands(array $scope, string $lang_code, array $commands);

    /**
     * Clear bot commands for the specified bot scope and language code
     *
     * @param array $scope Command scope @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * @param string $lang_code Language code
     * 
     *
     * @return array
     */
    public function resetBotCommands(array $scope, string $lang_code);

    /**
     * Obtain a list of bot commands for the specified bot scope and language code
     *
     * @param array $scope Command scope @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * @param string $lang_code Language code
     * 
     *
     * @return array
     */
    public function getBotCommands(array $scope, string $lang_code);

    /**
     * Sets the [menu button action »](https://core.telegram.org/api/bots/menu) for a given user or for all users
     *
     * @param array $user_id User ID @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * @param array $button Bot menu button action @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * 
     *
     * @return array
     */
    public function setBotMenuButton(array $user_id, array $button);

    /**
     * Gets the menu button action for a given user or for all users, previously set using [bots.setBotMenuButton](https://docs.madelineproto.xyz/API_docs/methods/bots.setBotMenuButton.html); users can see this information in the [botInfo](https://docs.madelineproto.xyz/API_docs/constructors/botInfo.html) constructor.
     *
     * @param array $user_id User ID or empty for the default menu button. @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * 
     *
     * @return array
     */
    public function getBotMenuButton(array $user_id);

    /**
     * Set the default [suggested admin rights](https://core.telegram.org/api/rights#suggested-bot-rights) for bots being added as admins to channels, see [here for more info on how to handle them »](https://core.telegram.org/api/rights#suggested-bot-rights).
     *
     * @param array $admin_rights Admin rights @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * 
     *
     * @return array
     */
    public function setBotBroadcastDefaultAdminRights(array $admin_rights);

    /**
     * Set the default [suggested admin rights](https://core.telegram.org/api/rights#suggested-bot-rights) for bots being added as admins to groups, see [here for more info on how to handle them »](https://core.telegram.org/api/rights#suggested-bot-rights).
     *
     * @param array $admin_rights Admin rights @see https://docs.madelineproto.xyz/API_docs/types/array.html
     * 
     *
     * @return array
     */
    public function setBotGroupDefaultAdminRights(array $admin_rights);
}
