<?php declare(strict_types=1);
/**
 * This file is automatic generated by build_docs.php file
 * and is used only for autocomplete in multiple IDE
 * don't modify manually.
 */

namespace danog\MadelineProto\Namespace;

interface Chatlists
{
    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     * @param list<array|int|string>|array<never, never> $peers Array of  @see https://docs.madelineproto.xyz/API_docs/types/InputPeer.html
     * @return array{_: 'chatlists.exportedChatlistInvite', filter: array{_: 'dialogFilter', contacts: bool, non_contacts: bool, groups: bool, broadcasts: bool, bots: bool, exclude_muted: bool, exclude_read: bool, exclude_archived: bool, id: int, title: string, emoticon: string, pinned_peers: list<array|int|string>, include_peers: list<array|int|string>, exclude_peers: list<array|int|string>}|array{_: 'dialogFilterDefault'}|array{_: 'dialogFilterChatlist', has_my_invites: bool, id: int, title: string, emoticon: string, pinned_peers: list<array|int|string>, include_peers: list<array|int|string>}, invite: array{_: 'exportedChatlistInvite', title: string, url: string, peers: list<array|int|string>}} @see https://docs.madelineproto.xyz/API_docs/types/chatlists.ExportedChatlistInvite.html
     */
    public function exportChatlistInvite(array $chatlist, string $title = '', array $peers = []): array;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     */
    public function deleteExportedInvite(array $chatlist, string $slug = ''): bool;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     * @param list<array|int|string>|array<never, never> $peers Array of  @see https://docs.madelineproto.xyz/API_docs/types/InputPeer.html
     * @return array{_: 'exportedChatlistInvite', title: string, url: string, peers: list<array|int|string>} @see https://docs.madelineproto.xyz/API_docs/types/ExportedChatlistInvite.html
     */
    public function editExportedInvite(array $chatlist, string $slug = '', string $title = '', array $peers = []): array;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     * @return array{_: 'chatlists.exportedInvites', invites: list<array{_: 'exportedChatlistInvite', title: string, url: string, peers: list<array|int|string>}>, chats: list<array|int|string>, users: list<array|int|string>} @see https://docs.madelineproto.xyz/API_docs/types/chatlists.ExportedInvites.html
     */
    public function getExportedInvites(array $chatlist): array;

    /**
     *
     *
     * @return array{_: 'chatlists.chatlistInviteAlready', filter_id: int, missing_peers: list<array|int|string>, already_peers: list<array|int|string>, chats: list<array|int|string>, users: list<array|int|string>}|array{_: 'chatlists.chatlistInvite', title: string, emoticon: string, peers: list<array|int|string>, chats: list<array|int|string>, users: list<array|int|string>} @see https://docs.madelineproto.xyz/API_docs/types/chatlists.ChatlistInvite.html
     */
    public function checkChatlistInvite(string $slug = ''): array;

    /**
     *
     *
     * @param list<array|int|string>|array<never, never> $peers Array of  @see https://docs.madelineproto.xyz/API_docs/types/InputPeer.html
     * @return array @see https://docs.madelineproto.xyz/API_docs/types/Updates.html
     */
    public function joinChatlistInvite(string $slug = '', array $peers = []): array;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     * @return array{_: 'chatlists.chatlistUpdates', missing_peers: list<array|int|string>, chats: list<array|int|string>, users: list<array|int|string>} @see https://docs.madelineproto.xyz/API_docs/types/chatlists.ChatlistUpdates.html
     */
    public function getChatlistUpdates(array $chatlist): array;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     * @param list<array|int|string>|array<never, never> $peers Array of  @see https://docs.madelineproto.xyz/API_docs/types/InputPeer.html
     * @return array @see https://docs.madelineproto.xyz/API_docs/types/Updates.html
     */
    public function joinChatlistUpdates(array $chatlist, array $peers = []): array;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     */
    public function hideChatlistUpdates(array $chatlist): bool;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     * @return list<array|int|string> Array of  @see https://docs.madelineproto.xyz/API_docs/types/Peer.html
     */
    public function getLeaveChatlistSuggestions(array $chatlist): array;

    /**
     *
     *
     * @param array{_: 'inputChatlistDialogFilter', filter_id?: int} $chatlist @see https://docs.madelineproto.xyz/API_docs/types/InputChatlist.html
     * @param list<array|int|string>|array<never, never> $peers Array of  @see https://docs.madelineproto.xyz/API_docs/types/InputPeer.html
     * @return array @see https://docs.madelineproto.xyz/API_docs/types/Updates.html
     */
    public function leaveChatlist(array $chatlist, array $peers = []): array;
}
