FROM php:8.2-fpm-bullseye

ADD https://raw.githubusercontent.com/danog/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/

RUN curl -sSLf https://github.com/danog/PrimeModule-ext/archive/refs/tags/2.0.tar.gz | tar -xz && \
    cd PrimeModule-ext-2.0 && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -r PrimeModule-ext-2.0

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions ffi pq ev-beta eio-beta intl gmp mbstring pdo_mysql xml dom curl zip opcache && \
    rm /usr/local/bin/install-php-extensions

ADD ./tests/dockerfiles/php.ini /usr/local/etc/php/php.ini

CMD ["php"]
