FROM php:8.2-fpm-alpine

RUN apk add make g++ && \
    curl -sSLf https://github.com/danog/PrimeModule-ext/archive/refs/tags/2.0.tar.gz | tar -xz && \
    cd PrimeModule-ext-2.0 && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -r PrimeModule-ext-2.0 && \
    apk del make g++

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions ffi pq uv-beta memprof intl gmp mbstring pdo_mysql xml dom zip opcache && \
    rm /usr/local/bin/install-php-extensions

ADD ./tests/dockerfiles/php.ini /usr/local/etc/php/php.ini

WORKDIR /app

CMD ["php", "/app/bot.php"]
