<?php declare(strict_types=1);
/**
 * This file is automatically generated by the build_docs.php file
 * and is used only for autocompletion in multiple IDEs
 * don't modify it manually.
 */

namespace danog\MadelineProto\EventHandler;

/** @internal An internal interface used to avoid type errors when using simple filters. */
interface SimpleFilters extends \danog\MadelineProto\EventHandler\SimpleFilter\Ended, \danog\MadelineProto\EventHandler\SimpleFilter\FromAdmin, \danog\MadelineProto\EventHandler\SimpleFilter\FromAdminOrOutgoing, \danog\MadelineProto\EventHandler\SimpleFilter\HasAudio, \danog\MadelineProto\EventHandler\SimpleFilter\HasDocument, \danog\MadelineProto\EventHandler\SimpleFilter\HasDocumentPhoto, \danog\MadelineProto\EventHandler\SimpleFilter\HasGif, \danog\MadelineProto\EventHandler\SimpleFilter\HasMedia, \danog\MadelineProto\EventHandler\SimpleFilter\HasMultiplePoll, \danog\MadelineProto\EventHandler\SimpleFilter\HasNoMedia, \danog\MadelineProto\EventHandler\SimpleFilter\HasPhoto, \danog\MadelineProto\EventHandler\SimpleFilter\HasPoll, \danog\MadelineProto\EventHandler\SimpleFilter\HasQuizPoll, \danog\MadelineProto\EventHandler\SimpleFilter\HasRoundVideo, \danog\MadelineProto\EventHandler\SimpleFilter\HasSinglePoll, \danog\MadelineProto\EventHandler\SimpleFilter\HasSticker, \danog\MadelineProto\EventHandler\SimpleFilter\HasTopic, \danog\MadelineProto\EventHandler\SimpleFilter\HasVideo, \danog\MadelineProto\EventHandler\SimpleFilter\HasVoice, \danog\MadelineProto\EventHandler\SimpleFilter\Incoming, \danog\MadelineProto\EventHandler\SimpleFilter\IsEdited, \danog\MadelineProto\EventHandler\SimpleFilter\IsForwarded, \danog\MadelineProto\EventHandler\SimpleFilter\IsNotEdited, \danog\MadelineProto\EventHandler\SimpleFilter\IsReply, \danog\MadelineProto\EventHandler\SimpleFilter\IsReplyToSelf, \danog\MadelineProto\EventHandler\SimpleFilter\Outgoing, \danog\MadelineProto\EventHandler\SimpleFilter\Running
{
}
