<?php

declare(strict_types=1);

/**
 * APIFactory module.
 *
 * This file is part of MadelineProto.
 * MadelineProto is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * MadelineProto is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * You should have received a copy of the GNU General Public License along with MadelineProto.
 * If not, see <http://www.gnu.org/licenses/>.
 *
 * @author    Daniil Gentili <daniil@daniil.it>
 * @copyright 2016-2023 Daniil Gentili <daniil@daniil.it>
 * @license   https://opensource.org/licenses/AGPL-3.0 AGPLv3
 * @link https://docs.madelineproto.xyz MadelineProto documentation
 */

namespace danog\MadelineProto;

class APIFactory extends AbstractAPIFactory
{
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public stats $stats;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public folders $folders;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public langpack $langpack;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public phone $phone;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public stickers $stickers;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public payments $payments;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public bots $bots;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public channels $channels;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public help $help;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public upload $upload;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public photos $photos;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public updates $updates;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public messages $messages;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public contacts $contacts;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public users $users;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public account $account;
    /**
     * @internal this is a internal property generated by build_docs.php, don't change manually
     */
    public auth $auth;
}
