<?php declare(strict_types=1);

/**
 * This file is part of MadelineProto.
 * MadelineProto is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * MadelineProto is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * You should have received a copy of the GNU General Public License along with MadelineProto.
 * If not, see <http://www.gnu.org/licenses/>.
 *
 * @author    Daniil Gentili <daniil@daniil.it>
 * @copyright 2016-2025 Daniil Gentili <daniil@daniil.it>
 * @license   https://opensource.org/licenses/AGPL-3.0 AGPLv3
 * @link https://docs.madelineproto.xyz MadelineProto documentation
 */

// IMPORTANT NOTE: Please keep the above copyright notice intact if copying or rewriting this file in another language.

namespace danog\MadelineProto\Tgcalls;

use danog\MadelineProto\Exception;

/**
 * Translation between tgcalls' `InstanceV2Impl` signaling and SDP.
 *
 * Unlike `InstanceV2ReferenceImpl` (which simply ships an SDP blob back and forth), `InstanceV2Impl`
 * negotiates media with two structured messages: `InitialSetup` carries the ICE credentials and the
 * DTLS fingerprint, and `NegotiateChannels` carries one `MediaContent` per stream, describing its
 * SSRC, payload types and header extensions.
 *
 * Since MadelineProto drives a standard peer connection, this reads those messages out of the local
 * SDP offer and synthesizes the matching remote description from the peer's, exactly like
 * {@see GroupSdp} does for the group call SFU.
 *
 * @internal
 */
final class V2Sdp
{
    /**
     * Describe our local media in the form `NegotiateChannels` expects.
     *
     * @param string $offer        The SDP offer generated by the local peer connection.
     * @param bool   $outgoingOnly Omit rejected, inactive and receive-only m-lines.
     * @return list<array<string, mixed>> One `MediaContent` per selected m-line.
     */
    public static function contentsFromOffer(string $offer, bool $outgoingOnly = false): array
    {
        /** @var list<array<string, mixed>> $contents */
        $contents = [];
        /** @var array<string, mixed>|null $current */
        $current = null;

        foreach (self::lines($offer) as $line) {
            if (str_starts_with($line, 'm=')) {
                if ($current !== null) {
                    $contents[] = $current;
                }
                $parts = explode(' ', substr($line, 2));
                $kind = $parts[0];
                $current = [
                    'type' => $kind === 'video' ? 'video' : 'audio',
                    'ssrc' => '0',
                    'payloadTypes' => [],
                    'rtpExtensions' => [],
                    '_port' => (int) ($parts[1] ?? 0),
                    '_direction' => 'sendrecv',
                ];
                continue;
            }
            if ($current === null) {
                continue;
            }
            if (\in_array($line, ['a=sendrecv', 'a=sendonly', 'a=recvonly', 'a=inactive'], true)) {
                $current['_direction'] = substr($line, 2);
                continue;
            }
            if (str_starts_with($line, 'a=ssrc:') && $current['ssrc'] === '0') {
                $ssrc = (int) substr($line, 7);
                // tgcalls transmits SSRCs as unsigned decimal strings.
                $current['ssrc'] = (string) GroupSdp::toUnsignedSsrc($ssrc);
                continue;
            }
            if (str_starts_with($line, 'a=rtpmap:')) {
                /** @var list<array<string, mixed>> $payloadTypes */
                $payloadTypes = $current['payloadTypes'];
                $payloadTypes[] = self::payloadTypeFromRtpmap(substr($line, 9));
                $current['payloadTypes'] = $payloadTypes;
                continue;
            }
            if (str_starts_with($line, 'a=extmap:')) {
                $parts = explode(' ', substr($line, 9), 2);
                if (\count($parts) === 2) {
                    /** @var list<array{id: int, uri: string}> $extensions */
                    $extensions = $current['rtpExtensions'];
                    $extensions[] = ['id' => (int) $parts[0], 'uri' => trim($parts[1])];
                    $current['rtpExtensions'] = $extensions;
                }
                continue;
            }
            if (str_starts_with($line, 'a=fmtp:')) {
                self::applyFmtp($current, substr($line, 7));
                continue;
            }
            if (str_starts_with($line, 'a=rtcp-fb:')) {
                self::applyFeedback($current, substr($line, 10));
            }
        }
        if ($current !== null) {
            $contents[] = $current;
        }

        $result = [];
        foreach ($contents as $content) {
            $include = !$outgoingOnly || (
                $content['_port'] !== 0
                && \in_array($content['_direction'], ['sendrecv', 'sendonly'], true)
            );
            unset($content['_port'], $content['_direction']);
            if ($include) {
                $result[] = $content;
            }
        }
        return $result;
    }

    /**
     * Parse `payloadType clockRate[/channels]` out of an `a=rtpmap` line.
     *
     * @return array<string, mixed>
     */
    private static function payloadTypeFromRtpmap(string $value): array
    {
        [$id, $codec] = array_pad(explode(' ', $value, 2), 2, '');
        $parts = explode('/', $codec);
        return [
            'id' => (int) $id,
            'name' => $parts[0] ?? '',
            'clockrate' => (int) ($parts[1] ?? 0),
            'channels' => (int) ($parts[2] ?? 0),
            'feedbackTypes' => [],
            'parameters' => (object) [],
        ];
    }

    /**
     * Attach the `a=fmtp` parameters to the payload type they belong to.
     *
     * @param array<string, mixed> $content
     */
    private static function applyFmtp(array &$content, string $value): void
    {
        [$id, $params] = array_pad(explode(' ', $value, 2), 2, '');
        $parsed = [];
        foreach (explode(';', $params) as $pair) {
            $pair = trim($pair);
            if ($pair === '') {
                continue;
            }
            [$key, $val] = array_pad(explode('=', $pair, 2), 2, '');
            $parsed[trim($key)] = trim($val);
        }
        /** @var list<array<string, mixed>> $payloadTypes */
        $payloadTypes = $content['payloadTypes'];
        foreach ($payloadTypes as $index => $payloadType) {
            if ($payloadType['id'] === (int) $id) {
                $payloadTypes[$index]['parameters'] = $parsed === [] ? (object) [] : $parsed;
                break;
            }
        }
        $content['payloadTypes'] = $payloadTypes;
    }

    /**
     * Attach an `a=rtcp-fb` entry to the payload type it belongs to.
     *
     * @param array<string, mixed> $content
     */
    private static function applyFeedback(array &$content, string $value): void
    {
        $parts = explode(' ', $value);
        $id = (int) array_shift($parts);
        $type = array_shift($parts) ?? '';
        $subtype = implode(' ', $parts);
        /** @var list<array<string, mixed>> $payloadTypes */
        $payloadTypes = $content['payloadTypes'];
        foreach ($payloadTypes as $index => $payloadType) {
            if ($payloadType['id'] === $id) {
                /** @var list<array{type: string, subtype: string}> $feedback */
                $feedback = $payloadTypes[$index]['feedbackTypes'];
                $feedback[] = ['type' => $type, 'subtype' => $subtype];
                $payloadTypes[$index]['feedbackTypes'] = $feedback;
                break;
            }
        }
        $content['payloadTypes'] = $payloadTypes;
    }

    /**
     * Synthesize the remote description out of the peer's `InitialSetup` and `NegotiateChannels`.
     *
     * @param string               $offer        Our own local offer, used as the m-line template.
     * @param array<string, mixed> $initialSetup The peer's `InitialSetup` message.
     * @param list<array>          $contents     The peer's `MediaContent` list.
     * @param bool                 $answer       Whether the result is an answer to our offer.
     */
    public static function buildRemoteDescription(
        string $offer,
        array $initialSetup,
        array $contents,
        bool $answer
    ): string {
        $ufrag = (string) ($initialSetup['ufrag'] ?? '');
        $pwd = (string) ($initialSetup['pwd'] ?? '');
        if ($ufrag === '' || $pwd === '') {
            throw new Exception('The peer sent an InitialSetup without ICE credentials!');
        }

        $fingerprints = [];
        $setup = 'active';
        foreach ($initialSetup['fingerprints'] ?? [] as $fingerprint) {
            $fingerprints[] = 'a=fingerprint:'.$fingerprint['hash'].' '.$fingerprint['fingerprint'];
            $setup = (string) ($fingerprint['setup'] ?? $setup);
        }
        if ($fingerprints === []) {
            throw new Exception('The peer sent an InitialSetup without a DTLS fingerprint!');
        }
        // An answer may never say actpass: pick a concrete role opposite to ours.
        if ($answer && $setup === 'actpass') {
            $setup = 'active';
        }

        $result = [];
        $index = 0;
        $inMedia = false;
        $pending = [];
        $offeredContents = self::contentsFromOffer($offer);
        $mappedContents = [];
        $usedContents = [];
        foreach ($offeredContents as $mediaIndex => $offeredContent) {
            $offeredSsrc = (string) ($offeredContent['ssrc'] ?? '0');
            if ($offeredSsrc !== '0') {
                foreach ($contents as $contentIndex => $content) {
                    if (!isset($usedContents[$contentIndex]) && (string) ($content['ssrc'] ?? '0') === $offeredSsrc) {
                        $mappedContents[$mediaIndex] = $content;
                        $usedContents[$contentIndex] = true;
                        continue 2;
                    }
                }
            }
            foreach ($contents as $contentIndex => $content) {
                if (!isset($usedContents[$contentIndex]) && ($content['type'] ?? null) === ($offeredContent['type'] ?? null)) {
                    $mappedContents[$mediaIndex] = $content;
                    $usedContents[$contentIndex] = true;
                    continue 2;
                }
            }
            $mappedContents[$mediaIndex] = null;
        }
        $appendRtp = static function (array $content) use (&$result): void {
            foreach ($content['rtpExtensions'] ?? [] as $extension) {
                $result[] = 'a=extmap:'.$extension['id'].' '.$extension['uri'];
            }
            foreach ($content['payloadTypes'] ?? [] as $payloadType) {
                $line = 'a=rtpmap:'.$payloadType['id'].' '.$payloadType['name'].'/'.$payloadType['clockrate'];
                if (($payloadType['channels'] ?? 0) > 1) {
                    $line .= '/'.$payloadType['channels'];
                }
                $result[] = $line;
                foreach ($payloadType['feedbackTypes'] ?? [] as $feedback) {
                    $result[] = trim('a=rtcp-fb:'.$payloadType['id'].' '.$feedback['type'].' '.($feedback['subtype'] ?? ''));
                }
                $parameters = (array) ($payloadType['parameters'] ?? []);
                if ($parameters !== []) {
                    $pairs = [];
                    foreach ($parameters as $key => $value) {
                        $pairs[] = $key.'='.$value;
                    }
                    $result[] = 'a=fmtp:'.$payloadType['id'].' '.implode(';', $pairs);
                }
            }
        };

        $flush = static function () use (&$result, &$pending, &$index, $answer, $offeredContents, $mappedContents, $appendRtp, $fingerprints, $ufrag, $pwd, $setup): void {
            if ($pending === []) {
                return;
            }
            $content = $mappedContents[$index] ?? null;
            $offeredContent = $offeredContents[$index] ?? null;
            $index++;
            $result = array_merge($result, $pending);
            $pending = [];

            if ($content === null) {
                // Answers reject an unaccepted m-line. A renegotiation offer instead keeps an
                // inactive, reusable section, matching tgcalls' persistent channel ordering.
                $result[] = 'a=inactive';
                if (!$answer && $offeredContent !== null) {
                    $result[] = 'a=rtcp-mux';
                    $result[] = 'a=rtcp:9 IN IP4 0.0.0.0';
                    $appendRtp($offeredContent);
                    $result[] = 'a=ice-ufrag:'.$ufrag;
                    $result[] = 'a=ice-pwd:'.$pwd;
                    $result = array_merge($result, $fingerprints);
                    $result[] = 'a=setup:'.$setup;
                }
                return;
            }

            $result[] = 'a=sendrecv';
            $result[] = 'a=rtcp-mux';
            $result[] = 'a=rtcp:9 IN IP4 0.0.0.0';
            $appendRtp($content);
            $result[] = 'a=ice-ufrag:'.$ufrag;
            $result[] = 'a=ice-pwd:'.$pwd;
            $result = array_merge($result, $fingerprints);
            $result[] = 'a=setup:'.$setup;
            $ssrc = (int) ($content['ssrc'] ?? 0);
            if ($ssrc !== 0) {
                $result[] = 'a=ssrc:'.$ssrc.' cname:tgcalls'.$ssrc;
            }
        };

        foreach (self::lines($offer) as $line) {
            if (str_starts_with($line, 'm=')) {
                $flush();
                $inMedia = true;
                $content = $mappedContents[$index] ?? null;
                $formats = [];
                foreach ($content['payloadTypes'] ?? [] as $payloadType) {
                    $formats[] = (string) $payloadType['id'];
                }
                $kind = explode(' ', substr($line, 2))[0];
                if ($content === null && $answer) {
                    $parts = explode(' ', $line);
                    $parts[1] = '0';
                    $pending[] = implode(' ', $parts);
                } elseif ($content === null) {
                    $pending[] = $line;
                } else {
                    $pending[] = 'm='.$kind.' 9 UDP/TLS/RTP/SAVPF '.($formats === [] ? '0' : implode(' ', $formats));
                }
                $pending[] = 'c=IN IP4 0.0.0.0';
                continue;
            }
            if (!$inMedia) {
                $result[] = $line;
                continue;
            }
            if (str_starts_with($line, 'a=mid:')) {
                $pending[] = $line;
            }
        }
        $flush();

        return implode("\r\n", $result)."\r\n";
    }

    /**
     * @return list<string>
     */
    private static function lines(string $sdp): array
    {
        $lines = [];
        foreach (explode("\n", str_replace("\r\n", "\n", $sdp)) as $line) {
            $line = rtrim($line, "\r");
            if ($line !== '') {
                $lines[] = $line;
            }
        }
        return $lines;
    }

    /**
     * Read the ICE credentials and DTLS fingerprint out of our own local description.
     *
     * @return array{ufrag: string, pwd: string, fingerprints: list<array{hash: string, fingerprint: string, setup: string}>}
     */
    public static function initialSetupFromDescription(string $sdp, string $setup): array
    {
        $ufrag = '';
        $pwd = '';
        $fingerprints = [];
        foreach (self::lines($sdp) as $line) {
            if ($ufrag === '' && str_starts_with($line, 'a=ice-ufrag:')) {
                $ufrag = substr($line, 12);
            } elseif ($pwd === '' && str_starts_with($line, 'a=ice-pwd:')) {
                $pwd = substr($line, 10);
            } elseif ($fingerprints === [] && str_starts_with($line, 'a=fingerprint:')) {
                [$hash, $value] = array_pad(explode(' ', substr($line, 14), 2), 2, '');
                $fingerprints[] = ['hash' => $hash, 'fingerprint' => $value, 'setup' => $setup];
            }
        }
        return ['ufrag' => $ufrag, 'pwd' => $pwd, 'fingerprints' => $fingerprints];
    }
}
